version: '3.8'

services:
  nginx:
    image: nginx
    ports:
      - "443:443"
    volumes:
      - public_data:/var/www/html
    depends_on:
      - mariadb
      - wordpress
    env_file: .env

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    env_file: .env

  wordpress:
    build: ./requirements/wordpress
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - public_data:/var/www/wordpress/wp-content
    depends_on:
      - mariadb
    env_file: .env
    

volumes:
  db_data:
  public_data: 
