services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - public_data:/var/www/html
    depends_on:
      - wordpress
    env_file: .env
    networks:
      - frontend

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    ports: 
      - "3307:3307"
    stdin_open: true
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    env_file: .env
    networks:
      - backend

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - public_data:/var/www/wordpress/wp-content
    depends_on:
      - mariadb
    env_file: .env
    networks:
      - frontend
      - backend
    

volumes:
  db_data:
  public_data: 

networks:
  frontend:
  backend: