services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - "~/public_data:/var/www/html"
    depends_on:
      - wordpress
    env_file: .env
    networks:
      - frontend
    restart: unless-stopped

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    ports: 
      - "3306:3306"
    stdin_open: true
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - "~/public_data:/var/lib/mysql"
    env_file: .env
    networks:
      - backend

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - "~/public_data:/var/www/html"
    depends_on:
      - mariadb
    env_file: .env
    networks:
      - frontend
      - backend
    

volumes:
  public_data: 

networks:
  frontend:
  backend: